# Welcome to Jekyll!
#

# Site settings
title: Co-VidSpeak
description:
  Video-Supported Remote Communication
owner: CoughDrop, Inc. # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@covidspeak.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.covidspeak.org" # the base hostname & protocol for your site
social:
  github: https://github.com/open-aac/covidspeak
  # facebook-official: https://www.facebook.com/AACintheCloud/
  #email: /contact/
  #flickr:
  #instagram:
  # youtube-square: https://www.youtube.com/c/myCoughDropAAC
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
